//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoMDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostico
    {
        public int Id { get; set; }
        public int ConsultaId { get; set; }
        public string observacao { get; set; }
        public int TipoDiagnosticoId { get; set; }
    
        public virtual Consulta Consulta { get; set; }
        public virtual TipoDiagnostico TipoDiagnostico { get; set; }
    }
}
