//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoMDS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalDBContainer : DbContext
    {
        public HospitalDBContainer()
            : base("name=HospitalDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Paciente> PacienteSet { get; set; }
        public virtual DbSet<Medico> MedicoSet { get; set; }
        public virtual DbSet<Consulta> ConsultaSet { get; set; }
        public virtual DbSet<Medicamento> MedicamentoSet { get; set; }
        public virtual DbSet<Diagnostico> DiagnosticoSet { get; set; }
        public virtual DbSet<Sintoma> SintomaSet { get; set; }
        public virtual DbSet<TipoSintoma> TipoSintomaSet { get; set; }
        public virtual DbSet<TipoMedicamento> TipoMedicamentoSet { get; set; }
        public virtual DbSet<TipoDiagnostico> TipoDiagnosticoSet { get; set; }
        public virtual DbSet<Enfermeiro> EnfermeiroSet { get; set; }
    }
}
